### ISSUE TITLE
ToastrFlash onclick options

### ISSUE THREAD

**Issue by hcharly** [odai-alali/yii2-toastr#1]
Hi,
Testing the ToastrFlash in my project.
That's really a nice idea.
Everything is working smoothly but can't get the 'onclick' options to work.
Setting 'onclick' to anything else than null leads to a 'toastr error options.onclick is not a function'.
Thanks for any tips.

**Comment by odai-alali** [comment]
Hello @hcharly 

i updated the code, it should be working now... pass javascript function to the 'onclick' option like this:

``` php
<?= \odaialali\yii2toastr\ToastrFlash::widget([
        'options' => [
            'closeButton' => 'true',
            'progressBar'=>'ture',
            'onclick' => 'function(){alert("hi")}'
        ]
    ]);?>
```

Thanks for feedback.

**Comment by hcharly** [comment]
Thanks Odai-alali.
It works great.
