### ISSUE TITLE
unable to install your extension

### ISSUE THREAD

**Issue by ajkosh** [odai-alali/yii2-toastr#2]
i m getting this 
- The requested package odaialali/yii2-toastr could not be found in any version, there may be a typo in the package name.

**Comment by odai-alali** [comment]
could you provide me with the composer.json file to check the require section?

**Comment by ajkosh** [comment]
I changed to dev master then it is working, can help me to tell me how to set ajax base,I have controller that will read from dB and after regular time it fetch and show ,I saw docs but I did nt get how to call with your widget,how to pass in your widget and I tried to add button on message but it is not adding how to add becoz on button click I want to do action,please I need help

**Comment by ajkosh** [comment]
i need example to set button and onclick in widget,i did nt find ,i tried but not working.

**Comment by odai-alali** [comment]
you need to set the **feedUrl** attribute in the **ToastrAjaxFeed** widget to the rout of the actions that returns the feed array
the widget will request this action repeatedly according to the time you provided in **interval** attribute

lets suppose that the action that reads the notifications from DB is "actionNotifications" in the controller "SiteController" and you want to check for events every 3 seconds, then the widget call should look like this:

``` php
<?= \odaialali\yii2toastr\ToastrAjaxFeed::widget([
    /* route to the action used to export notifications */
    'feedUrl' => yii\helpers\Url::toRoute('/site/notifications'),
    /* time interval you want to check action for new notifications (in milliseconds) */
    'interval' => 3000,
    'options' => [
        /** Toastr Options */
    ]
]);?>
```

the **actionNotifications** that reads notifications from DB should return JSON encoded array that looks similar to this:

``` php
$ret = [
        [
            'type' => 'error',
            'message' => 'error message',
            'title' => 'Hey!'
        ],
        [
            'type' => 'info',
            /* 
             you can put html tags inside message like the following.
             set a unique id for each notification button to be able to process 
             click event for these buttons
            */
            'message' => 'another message <a href="#" class="btn btn-primary btn-notification" id="uid1">Click Me!</a>',
            'title' => 'Hello'
        ]
    ];
```

add click events like this

``` javascript
$(document).on( "click", "a.btn-notification", function(e) {
  e.preventDefault();
  //your logic goes here
});
```

hope that this helps you.
