### ISSUE TITLE
ToastrFlash without customStyle

### ISSUE THREAD

**Issue by maxodrom** [odai-alali/yii2-toastr#3]
**Question:**
I use in my project views only \odaialali\yii2toastr\ToastrFlash class to display session flashes.
But internally this class uses \odaialali\yii2toastr\Toastr in which defined:
**public $customStyle = true;**
How I can disable this in order to use native Toastr css styles coming with Bower?

**And second moment:**
In case when we use **public $customStyle = true** it causes to register \odaialali\yii2toastr\ToastrCustomAsset and uses **toastr-style-reset.css** stylesheet.
In this CSS file (in line 38) we see:
**background-image: url("../img/portlet-remove-icon-white.png") !important;**
But folder img and the image portlet-remove-icon-white.png is absent at all in your assets folder and somewhere else!
This is a bug.

**Comment by maxodrom** [comment]
And one more thing as a "pull-request" (small improvement for ToastrFlash):

``` php
class ToastrFlash extends \yii\base\Widget {
    ////////////////   DECLARE THAT IN ORDER TO WE CAN OVERRIDE customStyle coming from 
    ////////////////   \odaialali\yii2toastr\Toastr in cases where we use ONLY 
    ////////////////  ToastrFlash::widget() in our Views.
    public $customStyle = true;
    ////////////////--------------
    public $alertTypes = [
        'error'   => 'error',
        'danger'  => 'error',
        'success' => 'success',
        'info'    => 'info',
        'warning' => 'warning'
    ];

    public $options = [];

    public function init()
    {
        parent::init();

        $session = \Yii::$app->getSession();
        $flashes = $session->getAllFlashes();

        foreach ($flashes as $type => $data) {
            if (isset($this->alertTypes[$type])) {
                $data = (array) $data;
                foreach ($data as $message) {
                    echo Toastr::widget([
                        'toastType' => $this->alertTypes[$type],
                        'message' => $message,
                        'options' => $this->options,
                        //////////////////// AND HERE PASS IT TO THE WIDGET
                        'customStyle' => $this->customStyle 
                        ///////////////////////////
                    ]);
                }

                $session->removeFlash($type);
            }
        }
    }
}
```

This improvemant can easily solve my and other developers problem with your default $customStyle.

In my views I can simly do the following:

``` php
\odaialali\yii2toastr\ToastrFlash::widget([
    'customStyle' => false,
    'options' => Yii::$app->params['toastr.options']
]);
```

And all will work for me.

Thank you.

**Comment by odai-alali** [comment]
Thank you for your contribution, and sorry for being sooooo late

i was busy and away from keyboard, i couldn't find a pull request from you so i edited the files, this commit should solve this bugs

**Comment by maxodrom** [comment]
No problem. Thank you for your reply and some improvement your code base accordind my advice.
